version: '2.2'
services:
  # Headquarters database
  hqdb:
    init: true
    image: postgres:11.2-alpine
    # same configuration as here: https://github.com/MagFry/ProjectLanguage/blob/master/ProjectLanguage/settings.py#L79
    environment:
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_DB=IAP_project
  # Headquarters Backend
  hq:
    init: true
    image: iap-hq-backend:0.1.0
    ports:
      - 8000:8000
    links:
      # the container hqdb is known inside hq as: db
      - hqdb:db
  # Branch office database
  bodb:
    init: true
    image: postgres:11.2-alpine
    #network_mode: host
    environment:
      - POSTGRES_PASSWORD=my_pw
      - POSTGRES_DB=mydb
  # Branch office backend
  bo:
    init: true
    image: iap-bo-backend:0.1.0
    environment:
      - IAP_BO_SYNCHRONIZATION_FREQUENCY=60
    ports:
      - 8080:8080
    links:
      # the container bodb is known inside bo as: db
      - bodb:db
  # TODO:
  # Headquarters frontend
  # Branch office frontend
