#!/bin/bash

set -eu

command="$1"
case "${command}" in
  build_all)
      ./tasks build_hq_backend
      ./tasks build_bo_backend
      ./tasks build_hq_frontend
      ./tasks build_bo_frontend
      exit $?
      ;;
  build_hq_backend)
      if [[ ! -d "IAP_project" ]]; then
        git clone git@github.com:MagFry/IAP_project.git
        # git clone git@github.com:xmik/IAP_project.git
      fi
      cd IAP_project
      ./tasks docker_build
      exit $?
      ;;
  build_bo_backend)
      if [[ ! -d "iap-bo-backend" ]]; then
        git clone git@github.com:xmik/iap-bo-backend.git
      fi
      cd iap-bo-backend
      # compile the code, produce the binaries
      dojo "./tasks build"
      # or, if you have dotnet installed locally, run this instead:
      # ./tasks build
      ./tasks docker_build
      exit $?
      ;;
  build_hq_frontend)
      if [[ ! -d "iap-hq-front" ]]; then
        git clone git@github.com:maciekmichalik/iap-hq-front.git
        # git clone git@github.com:xmik/IAP_project.git
      fi
      cd iap-hq-front
      ./tasks docker_build
      exit $?
      ;;
  build_bo_frontend)
      if [[ ! -d "iap-bo-frontend" ]]; then
        git clone git@github.com:maciekmichalik/iap-bo-frontend.git
        # git clone git@github.com:xmik/IAP_project.git
      fi
      cd iap-bo-frontend
      ./tasks docker_build
      exit $?
      ;;
  up)
      docker-compose -f ./docker-compose.yml -p iap up -d
      exit $?
      ;;
  down)
      docker-compose -f ./docker-compose.yml -p iap down
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
